services:
  lembaran:
    build:
      context: .
      dockerfile: Dockerfile
    image: lembaran:latest
    container_name: lembaran-app
    ports:
      - "1400:1400"
    volumes:
      - lembaran-data:/app/data
    environment:
      - NODE_ENV=production
      - NEXT_TELEMETRY_DISABLED=1
      - DB_PATH=/app/data/.lembaran-db.json
    restart: always

volumes:
  lembaran-data:
