services:
  abelion-notes:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "1400:1400"
    environment:
      - NODE_ENV=production
      - NEXT_TELEMETRY_DISABLED=1
    restart: always
